2019-07-27 14:47:42,533 INFO: errors [in C:/Users/evillasante/Downloads/AMP-Tech-master3/Herokuapp/app.py:268]
2019-07-27 16:09:10,004 INFO: errors [in C:/Users/evillasante/Downloads/AMP-Tech-master3/Herokuapp/app.py:268]
2019-07-27 16:09:10,004 INFO: errors [in C:/Users/evillasante/Downloads/AMP-Tech-master3/Herokuapp/app.py:268]
2019-07-27 16:09:18,277 ERROR: Exception on / [GET] [in C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/evillasante/Downloads/AMP-Tech-master3/Herokuapp/app.py", line 56, in home
    disc = gd.items_folder(service,'Formatos_Calidad')
  File "C:\Users\evillasante\Downloads\AMP-Tech-master3\Herokuapp\googledrive.py", line 31, in items_folder
    result = [service.files().get(fileId=x['id'] ).execute() for x in result]
  File "C:\Users\evillasante\Downloads\AMP-Tech-master3\Herokuapp\googledrive.py", line 31, in <listcomp>
    result = [service.files().get(fileId=x['id'] ).execute() for x in result]
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 846, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 183, in _retry_request
    raise exception
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 175, in new_request
    redirections, connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1953, in request
    cachekey,
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1618, in _request
    conn, request_uri, method, body, headers
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1556, in _conn_request
    response = conn.getresponse()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\evillasante\Anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2488)
2019-07-27 16:09:18,277 ERROR: Exception on / [GET] [in C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/evillasante/Downloads/AMP-Tech-master3/Herokuapp/app.py", line 56, in home
    disc = gd.items_folder(service,'Formatos_Calidad')
  File "C:\Users\evillasante\Downloads\AMP-Tech-master3\Herokuapp\googledrive.py", line 31, in items_folder
    result = [service.files().get(fileId=x['id'] ).execute() for x in result]
  File "C:\Users\evillasante\Downloads\AMP-Tech-master3\Herokuapp\googledrive.py", line 31, in <listcomp>
    result = [service.files().get(fileId=x['id'] ).execute() for x in result]
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 846, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 183, in _retry_request
    raise exception
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 175, in new_request
    redirections, connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1953, in request
    cachekey,
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1618, in _request
    conn, request_uri, method, body, headers
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1556, in _conn_request
    response = conn.getresponse()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\evillasante\Anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2488)
2019-07-27 16:09:18,279 ERROR: Exception on / [GET] [in C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/evillasante/Downloads/AMP-Tech-master3/Herokuapp/app.py", line 56, in home
    disc = gd.items_folder(service,'Formatos_Calidad')
  File "C:\Users\evillasante\Downloads\AMP-Tech-master3\Herokuapp\googledrive.py", line 19, in items_folder
    f_id = service.files().list(q=query,pageToken=None).execute()['items'][0]['id']
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 846, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 183, in _retry_request
    raise exception
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 175, in new_request
    redirections, connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1953, in request
    cachekey,
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1618, in _request
    conn, request_uri, method, body, headers
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1556, in _conn_request
    response = conn.getresponse()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\evillasante\Anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2488)
2019-07-27 16:09:18,279 ERROR: Exception on / [GET] [in C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/evillasante/Downloads/AMP-Tech-master3/Herokuapp/app.py", line 56, in home
    disc = gd.items_folder(service,'Formatos_Calidad')
  File "C:\Users\evillasante\Downloads\AMP-Tech-master3\Herokuapp\googledrive.py", line 19, in items_folder
    f_id = service.files().list(q=query,pageToken=None).execute()['items'][0]['id']
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 846, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 183, in _retry_request
    raise exception
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 175, in new_request
    redirections, connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1953, in request
    cachekey,
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1618, in _request
    conn, request_uri, method, body, headers
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1556, in _conn_request
    response = conn.getresponse()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\evillasante\Anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2488)
2019-07-27 16:18:18,215 ERROR: Exception on / [GET] [in C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/evillasante/Downloads/AMP-Tech-master3/Herokuapp/app.py", line 56, in home
    disc = gd.items_folder(service,'Formatos_Calidad')
  File "C:\Users\evillasante\Downloads\AMP-Tech-master3\Herokuapp\googledrive.py", line 19, in items_folder
    f_id = service.files().list(q=query,pageToken=None).execute()['items'][0]['id']
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 846, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 183, in _retry_request
    raise exception
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 175, in new_request
    redirections, connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1953, in request
    cachekey,
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1618, in _request
    conn, request_uri, method, body, headers
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1556, in _conn_request
    response = conn.getresponse()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\evillasante\Anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2488)
2019-07-27 16:18:18,215 ERROR: Exception on / [GET] [in C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/evillasante/Downloads/AMP-Tech-master3/Herokuapp/app.py", line 56, in home
    disc = gd.items_folder(service,'Formatos_Calidad')
  File "C:\Users\evillasante\Downloads\AMP-Tech-master3\Herokuapp\googledrive.py", line 19, in items_folder
    f_id = service.files().list(q=query,pageToken=None).execute()['items'][0]['id']
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 846, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 183, in _retry_request
    raise exception
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 175, in new_request
    redirections, connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1953, in request
    cachekey,
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1618, in _request
    conn, request_uri, method, body, headers
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1556, in _conn_request
    response = conn.getresponse()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\evillasante\Anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2488)
2019-07-27 16:18:18,215 ERROR: Exception on / [GET] [in C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/evillasante/Downloads/AMP-Tech-master3/Herokuapp/app.py", line 56, in home
    disc = gd.items_folder(service,'Formatos_Calidad')
  File "C:\Users\evillasante\Downloads\AMP-Tech-master3\Herokuapp\googledrive.py", line 31, in items_folder
    result = [service.files().get(fileId=x['id'] ).execute() for x in result]
  File "C:\Users\evillasante\Downloads\AMP-Tech-master3\Herokuapp\googledrive.py", line 31, in <listcomp>
    result = [service.files().get(fileId=x['id'] ).execute() for x in result]
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 846, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 183, in _retry_request
    raise exception
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 175, in new_request
    redirections, connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1953, in request
    cachekey,
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1618, in _request
    conn, request_uri, method, body, headers
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1556, in _conn_request
    response = conn.getresponse()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\evillasante\Anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2488)
2019-07-27 16:18:18,215 ERROR: Exception on / [GET] [in C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/evillasante/Downloads/AMP-Tech-master3/Herokuapp/app.py", line 56, in home
    disc = gd.items_folder(service,'Formatos_Calidad')
  File "C:\Users\evillasante\Downloads\AMP-Tech-master3\Herokuapp\googledrive.py", line 31, in items_folder
    result = [service.files().get(fileId=x['id'] ).execute() for x in result]
  File "C:\Users\evillasante\Downloads\AMP-Tech-master3\Herokuapp\googledrive.py", line 31, in <listcomp>
    result = [service.files().get(fileId=x['id'] ).execute() for x in result]
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 846, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 183, in _retry_request
    raise exception
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 175, in new_request
    redirections, connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1953, in request
    cachekey,
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1618, in _request
    conn, request_uri, method, body, headers
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1556, in _conn_request
    response = conn.getresponse()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\evillasante\Anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2488)
2019-07-27 16:25:01,402 ERROR: Exception on / [GET] [in C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/evillasante/Downloads/AMP-Tech-master3/Herokuapp/app.py", line 56, in home
    disc = gd.items_folder(service,'Formatos_Calidad')
  File "C:\Users\evillasante\Downloads\AMP-Tech-master3\Herokuapp\googledrive.py", line 19, in items_folder
    f_id = service.files().list(q=query,pageToken=None).execute()['items'][0]['id']
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 846, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 183, in _retry_request
    raise exception
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 175, in new_request
    redirections, connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1953, in request
    cachekey,
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1618, in _request
    conn, request_uri, method, body, headers
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1556, in _conn_request
    response = conn.getresponse()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\evillasante\Anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2488)
2019-07-27 16:25:01,402 ERROR: Exception on / [GET] [in C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/evillasante/Downloads/AMP-Tech-master3/Herokuapp/app.py", line 56, in home
    disc = gd.items_folder(service,'Formatos_Calidad')
  File "C:\Users\evillasante\Downloads\AMP-Tech-master3\Herokuapp\googledrive.py", line 19, in items_folder
    f_id = service.files().list(q=query,pageToken=None).execute()['items'][0]['id']
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 846, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 183, in _retry_request
    raise exception
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 175, in new_request
    redirections, connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1953, in request
    cachekey,
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1618, in _request
    conn, request_uri, method, body, headers
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1556, in _conn_request
    response = conn.getresponse()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\evillasante\Anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2488)
2019-07-27 16:25:01,403 ERROR: Exception on / [GET] [in C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/evillasante/Downloads/AMP-Tech-master3/Herokuapp/app.py", line 56, in home
    disc = gd.items_folder(service,'Formatos_Calidad')
  File "C:\Users\evillasante\Downloads\AMP-Tech-master3\Herokuapp\googledrive.py", line 31, in items_folder
    result = [service.files().get(fileId=x['id'] ).execute() for x in result]
  File "C:\Users\evillasante\Downloads\AMP-Tech-master3\Herokuapp\googledrive.py", line 31, in <listcomp>
    result = [service.files().get(fileId=x['id'] ).execute() for x in result]
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 846, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 183, in _retry_request
    raise exception
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 175, in new_request
    redirections, connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1953, in request
    cachekey,
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1618, in _request
    conn, request_uri, method, body, headers
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1556, in _conn_request
    response = conn.getresponse()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\evillasante\Anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2488)
2019-07-27 16:25:01,403 ERROR: Exception on / [GET] [in C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/evillasante/Downloads/AMP-Tech-master3/Herokuapp/app.py", line 56, in home
    disc = gd.items_folder(service,'Formatos_Calidad')
  File "C:\Users\evillasante\Downloads\AMP-Tech-master3\Herokuapp\googledrive.py", line 31, in items_folder
    result = [service.files().get(fileId=x['id'] ).execute() for x in result]
  File "C:\Users\evillasante\Downloads\AMP-Tech-master3\Herokuapp\googledrive.py", line 31, in <listcomp>
    result = [service.files().get(fileId=x['id'] ).execute() for x in result]
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 846, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 183, in _retry_request
    raise exception
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 175, in new_request
    redirections, connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1953, in request
    cachekey,
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1618, in _request
    conn, request_uri, method, body, headers
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1556, in _conn_request
    response = conn.getresponse()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\evillasante\Anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2488)
2019-07-27 16:28:21,298 ERROR: Exception on / [GET] [in C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/evillasante/Downloads/AMP-Tech-master3/Herokuapp/app.py", line 56, in home
    disc = gd.items_folder(service,'Formatos_Calidad')
  File "C:\Users\evillasante\Downloads\AMP-Tech-master3\Herokuapp\googledrive.py", line 19, in items_folder
    f_id = service.files().list(q=query,pageToken=None).execute()['items'][0]['id']
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 846, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 183, in _retry_request
    raise exception
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 175, in new_request
    redirections, connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1953, in request
    cachekey,
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1618, in _request
    conn, request_uri, method, body, headers
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1556, in _conn_request
    response = conn.getresponse()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\evillasante\Anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2488)
2019-07-27 16:28:21,298 ERROR: Exception on / [GET] [in C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/evillasante/Downloads/AMP-Tech-master3/Herokuapp/app.py", line 56, in home
    disc = gd.items_folder(service,'Formatos_Calidad')
  File "C:\Users\evillasante\Downloads\AMP-Tech-master3\Herokuapp\googledrive.py", line 19, in items_folder
    f_id = service.files().list(q=query,pageToken=None).execute()['items'][0]['id']
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 846, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 183, in _retry_request
    raise exception
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 175, in new_request
    redirections, connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1953, in request
    cachekey,
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1618, in _request
    conn, request_uri, method, body, headers
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1556, in _conn_request
    response = conn.getresponse()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\evillasante\Anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2488)
2019-07-27 16:28:21,299 ERROR: Exception on / [GET] [in C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/evillasante/Downloads/AMP-Tech-master3/Herokuapp/app.py", line 56, in home
    disc = gd.items_folder(service,'Formatos_Calidad')
  File "C:\Users\evillasante\Downloads\AMP-Tech-master3\Herokuapp\googledrive.py", line 31, in items_folder
    result = [service.files().get(fileId=x['id'] ).execute() for x in result]
  File "C:\Users\evillasante\Downloads\AMP-Tech-master3\Herokuapp\googledrive.py", line 31, in <listcomp>
    result = [service.files().get(fileId=x['id'] ).execute() for x in result]
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 846, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 183, in _retry_request
    raise exception
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 175, in new_request
    redirections, connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1953, in request
    cachekey,
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1618, in _request
    conn, request_uri, method, body, headers
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1556, in _conn_request
    response = conn.getresponse()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\evillasante\Anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2488)
2019-07-27 16:28:21,299 ERROR: Exception on / [GET] [in C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/evillasante/Downloads/AMP-Tech-master3/Herokuapp/app.py", line 56, in home
    disc = gd.items_folder(service,'Formatos_Calidad')
  File "C:\Users\evillasante\Downloads\AMP-Tech-master3\Herokuapp\googledrive.py", line 31, in items_folder
    result = [service.files().get(fileId=x['id'] ).execute() for x in result]
  File "C:\Users\evillasante\Downloads\AMP-Tech-master3\Herokuapp\googledrive.py", line 31, in <listcomp>
    result = [service.files().get(fileId=x['id'] ).execute() for x in result]
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 846, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 183, in _retry_request
    raise exception
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\googleapiclient\http.py", line 164, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 175, in new_request
    redirections, connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1953, in request
    cachekey,
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1618, in _request
    conn, request_uri, method, body, headers
  File "C:\Users\evillasante\Anaconda3\lib\site-packages\httplib2\__init__.py", line 1556, in _conn_request
    response = conn.getresponse()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\evillasante\Anaconda3\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\evillasante\Anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\evillasante\Anaconda3\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2488)
